import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { openDatabase } from "../server/database";
import { applyMigrations } from "../server/migrations";
import { StaffService } from "./staff-service";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "dvorik-staff-service-"));
const database = openDatabase(path.join(root, "staff.sqlite"));
applyMigrations(database, path.resolve("src/staff/migrations"));
const service = new StaffService(database, () => "2026-07-27T00:00:00.000Z");
service.upsertIdentity({ userId: "u-1", status: "active" });
assert.deepEqual(service.saveProfile({ userId: "u-1", position: "Продавец", hiredOn: "2026-07-01", status: "active", idempotencyKey: "profile-1" }), { userId: "u-1", personnelNumber: undefined, position: "Продавец", hiredOn: "2026-07-01", dismissedOn: undefined, status: "active", version: 0 });
assert.equal(service.recordHrEvent({ userId: "u-1", type: "late", startDate: "2026-07-27", minutesLate: 5, actorId: "u-1", idempotencyKey: "hr-1" }).type, "late");
assert.equal(service.hrEvents({ userId: "u-1" }).length, 1);
service.upsertIdentity({ userId: "u-2", status: "active" });
const shiftA=service.saveShift({date:"2026-07-28",start:"09:00",end:"13:00",locationId:"loc-1",employeeIds:["u-1"],status:"scheduled",idempotencyKey:"shift-1"});
const shiftB=service.saveShift({date:"2026-07-29",start:"09:00",end:"13:00",locationId:"loc-1",employeeIds:["u-2"],status:"scheduled",idempotencyKey:"shift-2"});
assert.equal(service.schedule().length,2);
const exchange=service.createExchange({fromShiftId:shiftA.id,toShiftId:shiftB.id,actorId:"u-1",idempotencyKey:"exchange-1"});
assert.equal(service.resolveExchange({id:exchange.id,action:"accept",actorId:"u-2",idempotencyKey:"exchange-2"}).status,"accepted");
service.upsertIdentity({ userId: "u-3", status: "active" });
const rotation=service.commitRotation({startDate:"2026-08-01",endDate:"2026-08-02",locationId:"loc-1",employeeIds:["u-1","u-2"],idempotencyKey:"rotation-1"});
assert.equal(rotation.shiftIds.length,2);
const replacement=service.commitFutureReplacement({fromUserId:"u-1",toUserId:"u-3",startDate:"2026-08-01",endDate:"2026-08-01",idempotencyKey:"replacement-1"});
assert.equal(replacement.replacements.length,1);
assert.ok(database.query<{count:number}>("SELECT count(*) count FROM staff_event_outbox")[0].count >= 1);
assert.equal(database.query<{ count: number }>("SELECT count(*) count FROM sqlite_master WHERE type='table' AND name IN ('users','shifts','inventory_balances')")[0].count, 0);
database.close();
console.log("staff service tests passed");
