import type { EmployeeProfile,HrEvent,ScheduleDay,SellerShiftSwapRequest,Shift,ShiftExchangeRequest,ShiftSwapRequest } from "../shared/types";
import type { DatabaseContext,SqlValue } from "./database";
import { scheduleDayMapper,shiftAssignmentMapper,shiftMapper,shiftSwapRequestMapper } from "./mappers/schedule";
type Row=Readonly<Record<string,unknown>>;
function shiftFromRow(database:DatabaseContext,row:Row):{shift:Shift;revision:string}{
  const mapped=shiftMapper.fromRow(row);
  const employeeIds=database.query<Row>("SELECT * FROM shift_assignments WHERE shift_id = ? ORDER BY user_id",[mapped.id]).map((assignment)=>shiftAssignmentMapper.fromRow(assignment).userId);
  const {scheduleDayId:_scheduleDayId,version:_version,createdByUserId:_createdByUserId,createdAt:_createdAt,updatedAt:_updatedAt,revision:_revision,...shift}=mapped;
  return {shift:{...shift,employeeIds},revision:mapped.revision};
}
export class SqlStaffQueryService{
  constructor(private readonly database:DatabaseContext){}
  shifts(input:Readonly<{userId?:string;from?:string;to?:string}>):Shift[]{const clauses:string[]=[];const parameters:SqlValue[]=[];if(input.from){clauses.push("s.local_date >= ?");parameters.push(input.from);}if(input.to){clauses.push("s.local_date <= ?");parameters.push(input.to);}if(input.userId){clauses.push("EXISTS (SELECT 1 FROM shift_assignments sa WHERE sa.shift_id = s.id AND sa.user_id = ?)");parameters.push(input.userId);}const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:"";return this.database.query<Row>(`SELECT s.* FROM shifts s ${where} ORDER BY s.local_date ASC, s.start_time ASC, s.id ASC`,parameters).map((row)=>shiftFromRow(this.database,row).shift);}
  shiftForWrite(id:string){const row=this.database.query<Row>("SELECT * FROM shifts WHERE id = ?",[id])[0];return row?shiftFromRow(this.database,row):undefined;}
  dayRevision(date:string,locationId:string){const row=this.database.query<Row>("SELECT * FROM schedule_days WHERE local_date = ? AND location_id = ?",[date,locationId])[0];return row?scheduleDayMapper.fromRow(row).version:null;}
  swaps(input:Readonly<{userId?:string}>):Array<ShiftSwapRequest|SellerShiftSwapRequest>{const rows=input.userId?this.database.query<Row>("SELECT * FROM shift_swap_requests WHERE from_user_id = ? OR to_user_id = ? ORDER BY created_at DESC, id DESC",[input.userId,input.userId]):this.database.query<Row>("SELECT * FROM shift_swap_requests ORDER BY created_at DESC, id DESC");return rows.map((row)=>{const {sourceShiftRevision:_sourceShiftRevision,version:_version,updatedAt:_updatedAt,resolvedAt:_resolvedAt,resolvedByUserId:_resolvedByUserId,revision:_revision,...swap}=shiftSwapRequestMapper.fromRow(row);return input.userId?(({fromShiftId:_fromShiftId,...seller})=>seller)(swap):swap;});}
  employeeProfiles():EmployeeProfile[]{return this.database.query<Row>("SELECT * FROM employee_profiles ORDER BY status,position COLLATE NOCASE,user_id").map((row)=>({userId:String(row.user_id),personnelNumber:row.personnel_number===null?undefined:String(row.personnel_number),position:String(row.position),hiredOn:String(row.hired_on),dismissedOn:row.dismissed_on===null?undefined:String(row.dismissed_on),status:row.status as EmployeeProfile["status"],version:Number(row.version)}));}
  hrEvents(input:Readonly<{userId?:string;from?:string;to?:string}>):HrEvent[]{const clauses:string[]=[];const parameters:SqlValue[]=[];if(input.userId){clauses.push("user_id=?");parameters.push(input.userId);}if(input.from){clauses.push("end_date>=?");parameters.push(input.from);}if(input.to){clauses.push("start_date<=?");parameters.push(input.to);}const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:"";return this.database.query<Row>(`SELECT * FROM hr_events ${where} ORDER BY start_date DESC,created_at DESC,id DESC`,parameters).map((row)=>({id:String(row.id),userId:String(row.user_id),type:row.type as HrEvent["type"],startDate:String(row.start_date),endDate:String(row.end_date),shiftId:row.shift_id===null?undefined:String(row.shift_id),minutesLate:row.minutes_late===null?undefined:Number(row.minutes_late),comment:String(row.comment),createdByUserId:String(row.created_by_user_id),createdAt:String(row.created_at)}));}
  exchanges(userId?:string):ShiftExchangeRequest[]{const rows=userId?this.database.query<Row>("SELECT * FROM shift_exchange_requests WHERE from_user_id=? OR to_user_id=? ORDER BY created_at DESC,id DESC",[userId,userId]):this.database.query<Row>("SELECT * FROM shift_exchange_requests ORDER BY created_at DESC,id DESC");return rows.map((row)=>{const parsed=JSON.parse(String(row.warning_json)) as {value?:{warnings?:string[]}};return{id:String(row.id),fromShiftId:String(row.from_shift_id),toShiftId:String(row.to_shift_id),fromUserId:String(row.from_user_id),toUserId:String(row.to_user_id),status:row.status as ShiftExchangeRequest["status"],warnings:parsed.value?.warnings??[],createdAt:String(row.created_at),resolvedAt:row.resolved_at===null?undefined:String(row.resolved_at)};});}
  days(input:Readonly<{userId?:string;from?:string;to?:string}>):ScheduleDay[]{const clauses:string[]=[];const parameters:SqlValue[]=[];if(input.from){clauses.push("d.local_date >= ?");parameters.push(input.from);}if(input.to){clauses.push("d.local_date <= ?");parameters.push(input.to);}if(input.userId){clauses.push("EXISTS (SELECT 1 FROM shifts s JOIN shift_assignments sa ON sa.shift_id = s.id WHERE s.local_date = d.local_date AND s.location_id = d.location_id AND sa.user_id = ?)");parameters.push(input.userId);}const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:"";return this.database.query<Row>(`SELECT d.* FROM schedule_days d ${where} ORDER BY d.local_date ASC, d.location_id ASC, d.id ASC`,parameters).map((row)=>{const {createdByUserId:_createdByUserId,createdAt:_createdAt,updatedAt:_updatedAt,revision:_revision,...day}=scheduleDayMapper.fromRow(row);return day;});}
}
