import assert from "node:assert/strict";
import { createFixedWindowRateLimiter, createHttpMetrics, crossOriginMutationRejected, invalidJsonPayload, isUnsafeApiMutation, requestCorrelationId, safeLogPath, securityHeaders } from "./runtime-observability";

assert.equal(requestCorrelationId("trace:abc-1"), "trace:abc-1");
assert.match(requestCorrelationId("bad value"), /^http:/);
assert.equal(safeLogPath("/api/saby/webhook/very-secret"), "/api/saby/webhook/[redacted]");
assert.equal(securityHeaders(true)["X-Frame-Options"], "DENY");
assert.match(String(securityHeaders(true)["Content-Security-Policy"]), /frame-ancestors 'none'/);
assert.equal("Strict-Transport-Security" in securityHeaders(false), false);
const metrics = createHttpMetrics();
metrics.begin();
metrics.begin();
metrics.complete(200);
metrics.complete(503);
assert.match(metrics.prometheus(), /dvorik_http_requests_total 2/);
assert.match(metrics.prometheus(), /dvorik_http_failures_total 1/);
assert.match(metrics.prometheus(), /status="503"/);
assert.equal(crossOriginMutationRejected({ method: "POST", path: "/api/stock/operations", origin: "https://evil.test", host: "dvorik.test", protocol: "https" }), true);
assert.equal(crossOriginMutationRejected({ method: "POST", path: "/api/stock/operations", origin: "https://dvorik.test", host: "dvorik.test", protocol: "https" }), false);
assert.equal(crossOriginMutationRejected({ method: "POST", path: "/api/telegram/webhook", origin: "https://evil.test", host: "dvorik.test", protocol: "https", secFetchSite: "cross-site" }), false);
assert.equal(crossOriginMutationRejected({ method: "POST", path: "/api/saby/webhook/secret", origin: "https://evil.test", host: "dvorik.test", protocol: "https", secFetchSite: "cross-site" }), false);
assert.equal(isUnsafeApiMutation("PATCH", "/api/products/p-1"), true);
assert.equal(isUnsafeApiMutation("GET", "/api/products"), false);
let time = 0;
const limiter = createFixedWindowRateLimiter({ limit: 2, windowMs: 1_000, now: () => time });
assert.equal(limiter.allow("ip").allowed, true);
assert.equal(invalidJsonPayload({ rows: [{ id: "safe" }] }), false);
assert.equal(invalidJsonPayload(JSON.parse('{"__proto__":{"polluted":true}}')), true);
assert.equal(invalidJsonPayload(Array.from({ length: 2_001 }, () => 1)), true);
assert.equal(limiter.allow("ip").allowed, true);
assert.equal(limiter.allow("ip").allowed, false);
time = 1_000;
assert.equal(limiter.allow("ip").allowed, true);
