import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { openDatabase } from "./database";
import { applyMigrations } from "./migrations";
import { createSqliteBackupBundle, restoreSqliteBackupBundle, verifySqliteBackupBundle } from "./sqlite-backup";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "dvorik-sqlite-backup-"));
const source = path.join(root, "source.sqlite");
const database = openDatabase(source);
database.executeScript("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL); INSERT INTO schema_migrations VALUES (1, datetime('now'));");
applyMigrations(database);
database.execute("INSERT INTO roles(id,name) VALUES ('seller','seller')");
const media = path.join(root, "media");
fs.mkdirSync(media);
fs.writeFileSync(path.join(media, "asset.txt"), "media-content");
const backup = createSqliteBackupBundle({ database, backupDirectory: path.join(root, "backups"), mediaDirectory: media, now: new Date("2026-07-15T01:02:03.004Z") });
assert.equal(verifySqliteBackupBundle(backup.path).migrations.length > 1, true);
database.execute("INSERT INTO roles(id,name) VALUES ('admin','admin')");
database.close();
const restored = path.join(root, "restored.sqlite");
const restoredMedia = path.join(root, "restored-media");
assert.equal(restoreSqliteBackupBundle({ bundlePath: backup.path, databasePath: restored, mediaDirectory: restoredMedia }).migrations.length > 1, true);
const restoredDatabase = openDatabase(restored);
assert.deepEqual(restoredDatabase.query<{ id: string }>("SELECT id FROM roles ORDER BY id"), [{ id: "seller" }]);
restoredDatabase.close();
assert.equal(fs.readFileSync(path.join(restoredMedia, "asset.txt"), "utf8"), "media-content");
fs.appendFileSync(path.join(backup.path, "database.sqlite"), "corrupt");
assert.throws(() => verifySqliteBackupBundle(backup.path), /Backup integrity mismatch/);
