import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { openDatabase } from "../server/database";
import { applyMigrations } from "../server/migrations";
import { buildNormalizedStateSql } from "../server/state-migration";
import { createSeedState } from "../server/store";

const root=fs.mkdtempSync(path.join(os.tmpdir(),"dvorik-staff-migration-"));
const coreFile=path.join(root,"core.sqlite");
const staffFile=path.join(root,"staff.sqlite");
const core=openDatabase(coreFile);
core.executeScript("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL); INSERT INTO schema_migrations VALUES (1,datetime('now'));");
applyMigrations(core);
core.executeScript(buildNormalizedStateSql(createSeedState()));
const sourceCounts={identities:core.query<{count:number}>("SELECT count(*) count FROM staff_user_snapshots")[0].count,shifts:core.query<{count:number}>("SELECT count(*) count FROM shifts")[0].count,assignments:core.query<{count:number}>("SELECT count(*) count FROM shift_assignments")[0].count};
core.close();
const environment={...process.env,DVORIK_SQLITE_FILE:coreFile,DVORIK_STAFF_SQLITE_FILE:staffFile};
const result=spawnSync(process.execPath,["--import","tsx",path.resolve("src/staff/migrate-from-core.ts")],{cwd:process.cwd(),env:environment,encoding:"utf8"});
assert.equal(result.status,0,result.stderr);
const staff=openDatabase(staffFile,{fileMustExist:true});
assert.equal(staff.query<{count:number}>("SELECT count(*) count FROM staff_identity_snapshots")[0].count,sourceCounts.identities);
assert.equal(staff.query<{count:number}>("SELECT count(*) count FROM staff_shifts")[0].count,sourceCounts.shifts);
assert.equal(staff.query<{count:number}>("SELECT count(*) count FROM staff_shift_assignments")[0].count,sourceCounts.assignments);
assert.equal(staff.query("PRAGMA foreign_key_check").length,0);
staff.close();
const repeated=spawnSync(process.execPath,["--import","tsx",path.resolve("src/staff/migrate-from-core.ts")],{cwd:process.cwd(),env:environment,encoding:"utf8"});
assert.notEqual(repeated.status,0);
assert.match(repeated.stderr,/STAFF_TARGET_NOT_EMPTY/);
console.log("staff migration tests passed");
